### ISSUE TITLE
[FEATURE]: Named volume bars with mute indicator

### ISSUE THREAD

**Issue by SimonC86** [XeroxDev/Loupedeck-plugin-VoiceMeeter#12]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Feature

First, thanks so much for creating this plugin - it works excellently!

A feature that I think would be exceptionally useful would be the name appearing at the bottom of the volume bars when they are assigned to the twist dials, and integrated mute indicator.

I primarily use these twist dials to control/mute (twist press) a number of audio channels (Music, Chrome, Mic, etc) and the only issue I've found is that once they are assigned there is no way of telling which is which, other than remembering.  The only solution I could find to this was to place the mute buttons next to each bar so I could see which each dial does, and if it was muted. However this takes up a lot of space and it would be really handy if all functionality could be combined in to just the volume bar. 

### Solution

If there was any way to have a visible label for each volume bar and visible mute indicator this could really clean up the interface for people interested in controlling multiple channels.

### Alternatives

I think there are a couple of ways this could be done, however this might be a niche use case, so understand if you don't feel it would be a useful addition overall.  Once again thanks for putting in the time to create this plugin!!

### Anything else?

![Possiblelayout](https://user-images.githubusercontent.com/109670837/179985178-1d290602-1d74-417f-9a35-c3f3fd5633e3.jpg)
![Screenshot 2022-07-20 132315](https://user-images.githubusercontent.com/109670837/179985202-e0b487ee-4129-4370-ab03-7de13f5237c3.jpg)

**Comment by XeroxDev** [comment]
Hey 👋

Thank you for this nice feedback and really good request.

I've decided to accept this request and hope I can add this feature.

/label +good +progress

**Comment by XeroxDev** [comment]
Small update!

I'll add your suggestions on my weekend session.

**Comment by SimonC86** [comment]
Amazing work on V 3.0!  Just set it up and it's all working great!  Thanks so much for adding this feature!!
