### ISSUE TITLE
[BUG]: strips/buses recognition breaks due to faulty characters

### ISSUE THREAD

**Issue by soerenkornetzki** [XeroxDev/Loupedeck-plugin-VoiceMeeter#16]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Feature

I want to control (gain, solo, mute) VoiceMeeters' hardware and **virtual (VAIO, AUX VAIO, VAIO3) inputs and outputs** with the VoiceMeeter Loupedeck plugin.

### Solution

Also add virtual (VAIO, AUX VAIO, VAIO3) inputs and output to the selection of the Loupedeck plugin.

### Alternatives

Could not find a workaround, besides manually control VoiceMeeter via mouse directly.

### Anything else?

Screenshot of the relevant strips in VoiceMeeter Potato:
![image](https://user-images.githubusercontent.com/36088772/191556618-9875ba22-ada3-44f6-a2e2-87e3a4a186c3.png)

Screenshot of the current (incomplete) VoiceMeeter Loupedeck plugin offerings:
![image](https://user-images.githubusercontent.com/36088772/191556953-8715f2b4-a86f-4a63-8622-2eecb28f9d5c.png)

**Comment by XeroxDev** [comment]
Hey. Sorry for the late response (I was a bit busy and sick as well).

I've looked into it and for me those additional inputs/outputs are available (I'm using Potato as well). 

And sadly I can't reproduce it. I'll try some things (like updating and so on) and maybe then I can reproduce it. I'll inform you if I find something new.

**Comment by soerenkornetzki** [comment]
Could you introduce some debug logging? And can you tell me how to "crank up" the logging (if possible) of VoiceMeeter to help investigate the issue?
I was thinking of dumping all data you receive from the VoiceMeeter communication, maybe we together can find the issue there (VM does not send virtual inputs/outputs, or it is actual an issue with your plugin).

**Comment by soerenkornetzki** [comment]
Haven't looked deeply, but could it be that you just detect the wrong edition of VoiceMeeter?

https://github.com/XeroxDev/Loupedeck-plugin-VoiceMeeter/blob/1cf98411550838503e4effb2c12dfd589ecadebd/VoiceMeeterPlugin/Library/Voicemeeter/Remote.cs#L230

The current version of Potato does not have any `8`:
![image](https://user-images.githubusercontent.com/36088772/197739485-1d46329f-667b-4e9d-911d-ddae92aaf8ce.png)

**Comment by soerenkornetzki** [comment]
The issue seems to be related to non A-Z 0-9 characters (e.g., whitespace) within the VoiceMeeter channel name. Changing all names (e.g., from "Local Mic In" to "Local_Mic_In") workaround the issue (all channels are now visible in Loupedeck).
However, there seems to be an issue related to whitespace and/or non-lower-ascii characters in the channel name.
