### ISSUE TITLE
[BUG]: DB Vakue of Gain not updateing

### ISSUE THREAD

**Issue by naiz0** [XeroxDev/Loupedeck-plugin-VoiceMeeter#17]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Question

Hi there,

I got my Live S today and the first Plugin i tried is this :-)
Thank you very much for this realy nice plugin.

If you see in the image, i added the Gain Buttons in the touch section, so i can see the DB Value of each channel.
But, when i rotate the stick, the values are not updating.

![loupdeckdb](https://user-images.githubusercontent.com/26410076/202808912-286263ec-2aa3-4b3e-9ada-8e7abf8bdf94.jpg)

When i change the screen and back to this, i get the real values. Also when i close and re-open the Loupdeck Software.
Is it possible that the values updating automatically?

thanks in advance,
greetings,
nico

PS: the mute buttons in the third line are Bus1 and Bus2, but the image says "Bus1" on both.

**Comment by XeroxDev** [comment]
Hello and thank you for contacting.

This seems to be a bug (it should update live / automatically). I'll look into it!

/label +bug -question +high +good
