### ISSUE TITLE
[QUESTION]: Screenshots show Fader values on touch bars, but they don't show up on my LD Live

### ISSUE THREAD

**Issue by bdux** [XeroxDev/Loupedeck-plugin-VoiceMeeter#20]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Question

Hello there, 
thanks for this plugin, it makes my life so much easier!

I have a question though... in some of the other issues, I can see that the gain volumes for the channel strips are shown either for the rotary encoders or for the touch buttons (for example: https://github.com/XeroxDev/Loupedeck-plugin-VoiceMeeter/issues/17#issue-1455869722), but this doesn't seem to happen on my Loupedeck. I only get the labels and no interactive displays.

Is there anything I am doing wrong?

I am running Loupedeck Software 5.4.1 on Windows 11, and have the latest firmware installed.

Thank you again!

**Comment by bdux** [comment]
Nevermind, I found my error.

I installed version 1.0 from the Marketplace. Downloaded v2 from here and it works now.

I will close this. :)

**Comment by XeroxDev** [comment]
Hey and thank you for your kind words!

Yes, sadly I didn't had time yet to update it on the marketplace yet. But I'll try it make it this weekend.
