### ISSUE TITLE
[FEATURE]: <title>

### ISSUE THREAD

**Issue by aztral** [XeroxDev/Loupedeck-plugin-VoiceMeeter#22]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Feature

Support for Macro buttons would be nice. The mute and in general all toggles doesnt work. 

Unsure if its a bug because it works with volume sliders it seems. (i have a macro bound with vol -+ keyboard buttons to control A1+2+3) but my macro button that mutes 3 strips for instance does not update on the toggle buttons on the loupedeck. It works fine otherwise  both ways when not using macro button.

**Comment by XeroxDev** [comment]
Hey. Thank you for the feature request. I'll looking into it, if it's possible to implement.

The toggle thing sounds like a bug (but I can't reproduce it), can you share more information? Maybe some screenshots or videos of the setup (and the faulty behavior)?
