### ISSUE TITLE
[FEATURE]: Change step size for pan_x and y

### ISSUE THREAD

**Issue by Pretagonist** [XeroxDev/Loupedeck-plugin-VoiceMeeter#23]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Feature

First off, I love your plugin and I find it very useful.

Currently the step size for pan_x on strips is 0.1.  The entire range seems to be 0 to 1 with 0.5 being the default center. This means that we only have 5 steps in either direction which isn't especially granular.

### Solution

Change the steps to something like 0.01 or perhaps even smaller to enable more granular control. 

I can do this via a macro buttons workaround but I lose the visual feedback and such.

**Comment by XeroxDev** [comment]
Thank you for your feedback! I'll (consider) adding it to the next version!

**Comment by Pretagonist** [comment]
Thanks! 

No hurry though, I figured out how to change and compile the plugin myself. Very easy build process, kudos.

**Comment by XeroxDev** [comment]
In the next version I'll add the possibility to specifically decide/choose from any step count you like.
