### ISSUE TITLE
[Bug]: Failed to install Plugin

### ISSUE THREAD

**Issue by Tailor84** [XeroxDev/Loupedeck-plugin-VoiceMeeter#32]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Current Behavior

I have tried to install the plugin 4.0.1 via “install plugin via file”. But every time I get the error message: “Installation of the plugin failed”

### Expected Behavior

i can install it :)

### Steps To Reproduce

1. Open Loupedeck software
2. go to "show or hide Plugins"
3. click the cogwheel
4. click on "install plugin with a file"
5. recieve Error Message

### OS

Windows

### OS Version

11

### Plugin Version

v4.0.1

### VoiceMeeter Version

v3.1.1.8

### How did you download the plugin?

GitHub

### Anything else?

![Screenshot 2024-11-12 213230](https://github.com/user-attachments/assets/b1220a89-b176-4073-9153-dbb483bcc4ad)

**Comment by XeroxDev** [comment]
Hey!

The latest major version (v4.x.x) of the Loupedeck Voicemeeter plugin is only compatible with the latest Loupedeck software version (v6.x.x). 

You've two options to resolve this problem. 

1. You've to upgrade your loupedeck software to v6 **(recommend)** 
2. You've to downgrade the plugin to v3

> [!IMPORTANT]  
> Downgrading to v3 of the plugin will result in less features and missing bug fixes. There's also no official support or upcoming updates for v3 anymore. It's highly recommended to always use the latest versions.

I hope I could help you with the problem.

I'm gonna /close this issue for now. Should the issue still persist or if you've any other questions regarding this issue, feel free to comment, ask or even reopen this issue again!

**Comment by Tailor84** [comment]
> Hey!
> 
> The latest major version (v4.x.x) of the Loupedeck Voicemeeter plugin is only compatible with the latest Loupedeck software version (v6.x.x).
> 
> You've two options to resolve this problem.
> 
> 1. You've to upgrade your loupedeck software to v6 **(recommend)**
> 2. You've to downgrade the plugin to v3
> 
> Important
> 
> Downgrading to v3 of the plugin will result in less features and missing bug fixes. There's also no official support or upcoming updates for v3 anymore. It's highly recommended to always use the latest versions.
> 
> I hope I could help you with the problem.
> 
> I'm gonna /close this issue for now. Should the issue still persist or if you've any other questions regarding this issue, feel free to comment, ask or even reopen this issue again!

oh no, I could have thought of that myself...

I don't have the latest software from Loupedeck yet, because I have the Loupedeck / Razer thing and they still recommend using 5.9.

Thank you very much for the quick help

**Comment by XeroxDev** [comment]
No worries! Like mentioned before, you can just downgrade the plugin to v3. Here's the link https://github.com/XeroxDev/Loupedeck-plugin-VoiceMeeter/releases/tag/v3.0.0
